# -*- coding: utf-8 -*-
"""kodluyoruz_python_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S8jAmhHVfFXlOicN3_h450QYFkmPu8IX
"""

import math

points = [(1,2),(2,3),(3,4),(4,5)]

def euclideanDistance(points1,points2):
  return math.sqrt((points2[0]-points1[0]) ** 2 + (points2[1]-points1[1]) ** 2)

distances = []

for i in range(len(points)):
  for k in range(i+1 , len(points)):
    distance = euclideanDistance(points[i], points[k])
    distances.append(distance)


min_distance = min(distances)

print(f"Min Distance = {min_distance}")